### ISSUE TITLE
Allow mapping of request parameters into SPARQL template slots

### ISSUE THREAD

**Issue by albertmeronyo** [the-open-university/basil#47]
It would be cool to allow API requests to come with GET/POST parameters, and allow those parameters to be mapped into certain dynamic areas of the stored SPARQL queries (this would need some SPARQL templating).

**Comment by enridaga** [comment]
It looks like this is one of the core features of the current implementation of Basil. See https://github.com/the-open-university/basil/wiki/SPARQL-variable-name-convention-for-WEB-API-parameters-mapping

**Comment by albertmeronyo** [comment]
Cool! I would advertise this a bit more :)

**Comment by enridaga** [comment]
You are perfectly right, and thank you for reporting this. In general we should add inline comments and descriptions in the UI.
There is an issue on Pesto about this now https://github.com/the-open-university/pesto/issues/7
