### ISSUE TITLE
Make it possible to use custom names (that is, not randomly generated) for the APIs.

### ISSUE THREAD

**Issue by barrynl** [the-open-university/basil#63]
I wanted to use Basil to expose a set of FAQ SPARQL questions and the randomly generated ID's make it less useful in this respect.

I guess Basil was more designed to let developers create their own REST APIs for a particular SPARQL endpoint?

**Comment by enridaga** [comment]
You can still deploy basil behind a HTTP server proxy like Apache, and map some APIs to specific paths.

**Comment by enridaga** [comment]
Also, see discussion #65

**Comment by enridaga** [comment]
Feature planned for 0.5.0
