### ISSUE TITLE
Does Basil support CONSTRUCT/UPDATE SPARQL queries?

### ISSUE THREAD

**Issue by barrynl** [the-open-university/basil#64]
See title.

**Comment by enridaga** [comment]
I know this is a very late answer, but No, although this can be supported in the future.

Practically, the only difference in the protocol is on the querystring parameter, that should be 'update'. 

Clearly, the configured endpoint should be the one supporting SPARQL Update.

**Comment by enridaga** [comment]
SPARQL Update is supported since 7744073
